/**
 * Copies a curated set of icons from @sketchyicons/data into
 * src/icons/builtin.ts so the library works out of the box with no runtime
 * dependency. Any other of its icons can be passed as demo.icon({ icon: { nodes } }).
 * Run with: node scripts/gen-icons.mjs
 */
import { writeFileSync } from 'node:fs';
import * as data from '@sketchyicons/data';

const OUT = 'src/icons/builtin.ts';

// Lucide names. Keep alphabetical; the generated module is diffed in review.
const NAMES = [
  'arrow-left',
  'arrow-right',
  'bell',
  'bookmark',
  'calendar',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle-alert',
  'circle-check',
  'circle-x',
  'copy',
  'download',
  'eye',
  'eye-off',
  'file',
  'folder',
  'globe',
  'heart',
  'house',
  'image',
  'info',
  'link',
  'list',
  'lock',
  'log-in',
  'log-out',
  'mail',
  'menu',
  'minus',
  'pause',
  'pencil',
  'play',
  'plus',
  'refresh-cw',
  'search',
  'send',
  'settings',
  'shopping-cart',
  'star',
  'trash-2',
  'triangle-alert',
  'upload',
  'user',
  'x',
];

const toComponent = (name) => data.componentNames[data.iconNames.indexOf(name)];

const entries = NAMES.map((name) => {
  const component = toComponent(name);
  const nodes = data[component];
  if (!Array.isArray(nodes)) throw new Error(`icon not found: ${name} (${component})`);
  for (const [tag, attrs] of nodes) {
    const keys = Object.keys(attrs);
    if (tag !== 'path' || !keys.every((k) => k === 'd' || k === 'fill')) {
      throw new Error(`icon ${name} has an unexpected node: ${tag} ${keys.join(',')}`);
    }
  }
  return `  ${JSON.stringify(name)}: { nodes: ${JSON.stringify(nodes)} },`;
}).join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-icons.mjs from @sketchyicons/data. Do not edit.
//
// Icon geometry is derived from Lucide (ISC, (c) Lucide Icons and Contributors)
// via sketchyicons (MIT, (c) Julien Montagne). See THIRD-PARTY-NOTICES.md.
import type { IconDef } from './types.js';

export const BUILTIN_ICONS: Readonly<Record<string, IconDef>> = {
${entries}
};
`,
);
console.log(`wrote ${OUT}: ${NAMES.length} icons`);
