/**
 * Converts a Hershey .jhf stroke font into the compact TypeScript module the
 * text renderer consumes. Run with: node scripts/gen-font.mjs
 *
 * .jhf format, one glyph per line (long glyphs may wrap onto further lines):
 *   cols 0-4   glyph number (ignored; the file is in ASCII order from 32)
 *   cols 5-7   number of coordinate pairs, including the first
 *   then pairs of characters, each coordinate being charCode - 'R'.
 *   The first pair is the glyph's left and right extent; " R" is pen-up.
 * Coordinates have y pointing down. In futural the baseline is y = 9 and
 * capitals reach y = -12, so the data below is shifted so that the baseline
 * is 0 and each glyph starts at x = 0.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'vendor/hershey/futural.jhf';
const OUT = 'src/text/fonts/hershey-sans.ts';
const BASELINE = 9;
const FIRST_CHAR = 32;

const raw = readFileSync(SRC, 'latin1').split('\n');
const records = [];
for (let i = 0; i < raw.length; i++) {
  const line = raw[i];
  if (!line.trim()) continue;
  const count = parseInt(line.slice(5, 8), 10);
  let body = line.slice(8);
  while (body.length < count * 2 && i + 1 < raw.length) {
    body += raw[++i];
  }
  records.push(body.slice(0, count * 2));
}

const glyphs = {};
let maxAscent = 0;
let maxDescent = 0;
records.forEach((body, index) => {
  const code = FIRST_CHAR + index;
  if (code > 126) return;
  const left = body.charCodeAt(0) - 82;
  const right = body.charCodeAt(1) - 82;
  const strokes = [];
  let current = [];
  for (let i = 2; i < body.length; i += 2) {
    const pair = body.slice(i, i + 2);
    if (pair === ' R') {
      if (current.length) strokes.push(current);
      current = [];
      continue;
    }
    const x = pair.charCodeAt(0) - 82 - left;
    const y = pair.charCodeAt(1) - 82 - BASELINE;
    current.push(x, y);
    maxAscent = Math.max(maxAscent, -y);
    maxDescent = Math.max(maxDescent, y);
  }
  if (current.length) strokes.push(current);
  glyphs[String.fromCharCode(code)] = { advance: right - left, strokes };
});

const entries = Object.entries(glyphs)
  .map(([ch, g]) => `  ${JSON.stringify(ch)}: [${g.advance}, ${JSON.stringify(g.strokes)}],`)
  .join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-font.mjs from ${SRC}. Do not edit.
//
// The Hershey Fonts were originally created by Dr. A. V. Hershey while working
// at the U. S. National Bureau of Standards. The format of the source data was
// originally created by James Hurt, Cognition, Inc. See vendor/hershey/LICENSE.
import type { StrokeFontData } from '../font.js';

export const HERSHEY_SANS: StrokeFontData = {
  name: 'hershey-sans',
  unitsPerEm: 32,
  ascent: ${maxAscent},
  descent: ${maxDescent},
  capHeight: 21,
  glyphs: {
${entries}
  },
};
`,
);
console.log(`wrote ${OUT}: ${Object.keys(glyphs).length} glyphs, ascent ${maxAscent}, descent ${maxDescent}`);
